[package]
name = "lizard"
description = "Decompresses LZ4 files with a custom magic header."
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
lz4_flex = "0.11"
